package com.example.upiapp.adapters;

import android.content.Context;
import android.content.Intent;
import android.graphics.Color;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;

import com.example.upiapp.R;
import com.example.upiapp.TransactionDetailsActivity;
import com.example.upiapp.models.Transaction;

import java.util.List;

public class TransactionAdapter extends RecyclerView.Adapter<TransactionAdapter.TransactionViewHolder> {

    private final List<Transaction> transactionList;

    public TransactionAdapter(List<Transaction> transactionList) {
        this.transactionList = transactionList;
    }

    @NonNull
    @Override
    public TransactionViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_transaction, parent, false);
        return new TransactionViewHolder(view);
    }

    @Override
    public void onBindViewHolder(@NonNull TransactionViewHolder holder, int position) {
        Transaction transaction = transactionList.get(position);

        // --- MAPPING DATA TO THE CORRECT VIEWS (using transaction data) ---
        holder.textReceiver.setText(transaction.getReceiverId());

        // Since your XML uses text_timestamp, we'll map the transaction message/reason here
        // as the actual timestamp is usually handled elsewhere or autogenerated.
        // We will display the transaction reason/message in the timestamp field.
        holder.textTimestamp.setText(transaction.getMessage());

        holder.textAmount.setText("₹ " + String.format("%.2f", transaction.getAmount()));
        holder.textStatus.setText(transaction.getStatus() + " (Risk: " + transaction.getRiskScore() + ")");

        // Set status color based on decision
        String status = transaction.getStatus();
        int color;
        if (status.equals("APPROVED")) {
            color = Color.parseColor("#4CAF50"); // Green
        } else if (status.equals("FLAGGED")) {
            color = Color.parseColor("#FF9800"); // Orange/Yellow
        } else { // BLOCKED
            color = Color.RED; // Red
        }
        holder.textStatus.setTextColor(color);

        // --- Implement click listener to open details activity ---
        holder.itemView.setOnClickListener(v -> {
            Context context = v.getContext();
            Intent intent = new Intent(context, TransactionDetailsActivity.class);

            // Pass all the transaction data required by TransactionDetailsActivity
            intent.putExtra("STATUS", transaction.getStatus());
            intent.putExtra("RECEIVER", transaction.getReceiverId());
            intent.putExtra("AMOUNT", transaction.getAmount());
            intent.putExtra("MESSAGE", transaction.getMessage());
            intent.putExtra("RISK_SCORE", String.valueOf(transaction.getRiskScore()));
            intent.putExtra("REASON", transaction.getReason());

            context.startActivity(intent);
        });
    }

    @Override
    public int getItemCount() {
        return transactionList.size();
    }

    static class TransactionViewHolder extends RecyclerView.ViewHolder {
        // Corrected variables to match the IDs in item_transaction.xml
        TextView textReceiver, textAmount, textStatus, textTimestamp;

        TransactionViewHolder(View itemView) {
            super(itemView);

            // Mapped to the actual IDs from your XML
            textReceiver = itemView.findViewById(R.id.text_receiver);
            textAmount = itemView.findViewById(R.id.text_amount);
            textStatus = itemView.findViewById(R.id.text_status);
            textTimestamp = itemView.findViewById(R.id.text_timestamp);
        }
    }
}